import { featuredProducts } from "@/lib/shared/constants/site";

export const fallbackProducts = [
  ...featuredProducts,
  {
    id: "citrus-crate",
    name: "Citrus Sunrise Crate",
    category: "Fresh Picks",
    description: "Bright oranges, lemons, and grapefruit curated for breakfast tables and juice bars.",
    image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=900&q=80",
    price: 26.4,
    discountPercent: 8,
    rating: 4.6,
    stock: 30,
    isActive: true,
  },
  {
    id: "garden-salad-kit",
    name: "Garden Salad Kit",
    category: "Bundles",
    description: "Washed greens, crunchy toppings, and a herb vinaigrette designed for quick lunches.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    price: 19.95,
    discountPercent: 5,
    rating: 4.7,
    stock: 18,
    isActive: true,
  },
  {
    id: "artisan-pantry-pack",
    name: "Artisan Pantry Pack",
    category: "Pantry",
    description: "Olive oil, sea salt, crackers, and pantry essentials styled as a premium shelf drop.",
    image: "https://images.unsplash.com/photo-1506617564039-2f3b650b7010?auto=format&fit=crop&w=900&q=80",
    price: 34.5,
    discountPercent: 0,
    rating: 4.5,
    stock: 12,
    isActive: true,
  },
  {
    id: "vital-water-5gal",
    name: "Vital Pure Water 5-Gallon Tank",
    category: "Beverages",
    description: "Pure drinking water in a 5-gallon tank. Choose small or large format for home or office delivery.",
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=900&q=80",
    price: 3.5,
    discountPercent: 0,
    rating: 4.5,
    stock: 50,
    isActive: true,
    // Demo product with multiple variants
    variants: [
      {
        id: "vital-water-5gal-small",
        name: "Small - 5 Gallon",
        sku: "VITAL-SML-5G",
        price: 3.5,
        discountPercent: 0,
        stock: 50,
      },
      {
        id: "vital-water-5gal-large",
        name: "Large - 5 Gallon Premium",
        sku: "VITAL-LRG-5G",
        price: 100,
        discountPercent: 0,
        stock: 20,
      },
    ],
    isVariant: true,
    displayPrice: 3.5,
    displayDiscountPercent: 0,
  },
].map((product) => ({
  stock: product.stock ?? 24,
  isActive: product.isActive ?? true,
  comments: [],
  variants: product.variants || [],
  isVariant: product.isVariant || false,
  displayPrice: product.displayPrice || product.price,
  displayDiscountPercent: product.displayDiscountPercent ?? product.discountPercent ?? 0,
  ...product,
}));
