// ─────────────────────────────────────────────────────────────────────────────
// Report Management registry — single source of truth shared by the API
// (dataset builders, CSV/PDF exporters) and the admin UI (table renderer).
// Every report resolves to the same dataset shape:
//   { columns, rows, summary, totalRow, meta }
// ─────────────────────────────────────────────────────────────────────────────

export const REPORT_CATEGORIES = [
  { key: "sales", label: "Sales Reports" },
  { key: "orders", label: "Order Reports" },
  { key: "inventory", label: "Inventory Reports" },
  { key: "additional", label: "Additional Reports" },
];

const DATE_RANGE_FILTER = { key: "range", type: "daterange", label: "Date range" };

export const REPORTS = [
  // ── A. Sales Reports ───────────────────────────────────────────────────────
  {
    id: "daily-sales",
    name: "Daily Sales Report",
    category: "sales",
    description: "All sales transactions made during the selected period, across POS and online channels.",
    defaultRange: "today",
    defaultSort: { sort: "datetime", dir: "desc" },
    columns: [
      { key: "saleId", label: "Sale ID", type: "text", sortable: true },
      { key: "datetime", label: "Date & Time", type: "datetime", sortable: true },
      { key: "cashier", label: "Cashier", type: "text", sortable: true },
      { key: "customer", label: "Customer", type: "text", sortable: true },
      { key: "items", label: "Items", type: "int", sortable: true, align: "right" },
      { key: "subtotal", label: "Subtotal", type: "money", sortable: true, align: "right" },
      { key: "discount", label: "Discount", type: "money", sortable: true, align: "right" },
      { key: "total", label: "Total Amount", type: "money", sortable: true, align: "right" },
      { key: "paymentMethod", label: "Payment", type: "text", sortable: true },
      { key: "channel", label: "Channel", type: "text", sortable: true },
      { key: "status", label: "Status", type: "status", sortable: true },
    ],
    filters: ["range", "cashier", "paymentMethod", "saleStatus", "channel"],
    summaryCards: [
      { key: "totalTransactions", label: "Total Transactions", type: "int" },
      { key: "itemsSold", label: "Items Sold", type: "int" },
      { key: "grossSales", label: "Gross Sales", type: "money" },
      { key: "totalDiscount", label: "Total Discount", type: "money" },
      { key: "netSales", label: "Net Sales", type: "money" },
      { key: "cashSales", label: "Cash Sales", type: "money" },
      { key: "khqrSales", label: "KHQR Sales", type: "money" },
    ],
    totalRowKeys: ["items", "subtotal", "discount", "total"],
  },
  {
    id: "sales-summary",
    name: "Sales Summary Report",
    category: "sales",
    description: "Day-by-day sales performance for the selected period.",
    defaultRange: "this_month",
    defaultSort: { sort: "date", dir: "desc" },
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "transactions", label: "Transactions", type: "int", sortable: true, align: "right" },
      { key: "itemsSold", label: "Items Sold", type: "int", sortable: true, align: "right" },
      { key: "grossSales", label: "Gross Sales", type: "money", sortable: true, align: "right" },
      { key: "discount", label: "Discount", type: "money", sortable: true, align: "right" },
      { key: "netSales", label: "Net Sales", type: "money", sortable: true, align: "right" },
      { key: "cash", label: "Cash", type: "money", sortable: true, align: "right" },
      { key: "khqr", label: "KHQR", type: "money", sortable: true, align: "right" },
    ],
    filters: ["range", "channel"],
    summaryCards: [
      { key: "totalSales", label: "Total Sales", type: "money" },
      { key: "totalTransactions", label: "Total Transactions", type: "int" },
      { key: "totalItemsSold", label: "Total Items Sold", type: "int" },
      { key: "averageTransaction", label: "Average Transaction", type: "money" },
    ],
    totalRowKeys: ["transactions", "itemsSold", "grossSales", "discount", "netSales", "cash", "khqr"],
  },
  {
    id: "best-selling",
    name: "Best-Selling Products Report",
    category: "sales",
    description: "Products ranked by sales volume and revenue contribution.",
    defaultRange: "this_month",
    defaultSort: { sort: "totalSales", dir: "desc" },
    columns: [
      { key: "rank", label: "Rank", type: "rank", sortable: false, align: "center" },
      { key: "product", label: "Product", type: "text", sortable: true },
      { key: "category", label: "Category", type: "text", sortable: true },
      { key: "qtySold", label: "Qty Sold", type: "int", sortable: true, align: "right" },
      { key: "unit", label: "Unit", type: "text", sortable: false },
      { key: "totalSales", label: "Total Sales", type: "money", sortable: true, align: "right" },
      { key: "percentOfSales", label: "% of Sales", type: "percent", sortable: true, align: "right" },
    ],
    filters: ["range", "category", "brand", "channel"],
    summaryCards: [
      { key: "uniqueProducts", label: "Products Sold", type: "int" },
      { key: "totalUnits", label: "Total Units", type: "int" },
      { key: "totalRevenue", label: "Total Revenue", type: "money" },
      { key: "topProduct", label: "Top Product", type: "text" },
    ],
    totalRowKeys: ["qtySold", "totalSales"],
  },
  {
    id: "payment-method",
    name: "Sales by Payment Method",
    category: "sales",
    description: "How customers paid — Cash and KHQR as recorded at the point of sale (POS KHQR is the cashier-recorded method, not a gateway transaction).",
    defaultRange: "this_month",
    defaultSort: { sort: "totalAmount", dir: "desc" },
    columns: [
      { key: "paymentMethod", label: "Payment Method", type: "text", sortable: true },
      { key: "transactions", label: "Transactions", type: "int", sortable: true, align: "right" },
      { key: "totalAmount", label: "Total Amount", type: "money", sortable: true, align: "right" },
      { key: "percentage", label: "Percentage", type: "percent", sortable: true, align: "right" },
    ],
    filters: ["range", "channel", "cashier", "paymentStatus"],
    summaryCards: [
      { key: "totalAmount", label: "Total Collected", type: "money" },
      { key: "totalTransactions", label: "Transactions", type: "int" },
      { key: "cashAmount", label: "Cash", type: "money" },
      { key: "khqrAmount", label: "KHQR", type: "money" },
    ],
    totalRowKeys: ["transactions", "totalAmount", "percentage"],
  },
  {
    id: "sales-channel",
    name: "Sales by Channel",
    category: "sales",
    description: "Sales comparison across POS, online, and wholesale channels.",
    defaultRange: "this_month",
    defaultSort: { sort: "netSales", dir: "desc" },
    columns: [
      { key: "channel", label: "Sales Channel", type: "text", sortable: true },
      { key: "transactions", label: "Transactions", type: "int", sortable: true, align: "right" },
      { key: "itemsSold", label: "Items Sold", type: "int", sortable: true, align: "right" },
      { key: "grossSales", label: "Gross Sales", type: "money", sortable: true, align: "right" },
      { key: "discount", label: "Discount", type: "money", sortable: true, align: "right" },
      { key: "netSales", label: "Net Sales", type: "money", sortable: true, align: "right" },
    ],
    filters: ["range"],
    summaryCards: [
      { key: "totalNetSales", label: "Total Net Sales", type: "money" },
      { key: "totalTransactions", label: "Total Transactions", type: "int" },
      { key: "totalItemsSold", label: "Total Items Sold", type: "int" },
      { key: "bestChannel", label: "Best Channel", type: "text" },
    ],
    totalRowKeys: ["transactions", "itemsSold", "grossSales", "discount", "netSales"],
  },

  // ── B. Order Reports ───────────────────────────────────────────────────────
  {
    id: "orders",
    name: "Order Report",
    category: "orders",
    description: "Customer orders submitted through the online ordering system, with fulfilment and payment status.",
    defaultRange: "this_month",
    defaultSort: { sort: "date", dir: "desc" },
    columns: [
      { key: "orderId", label: "Order ID", type: "text", sortable: true },
      { key: "date", label: "Date", type: "datetime", sortable: true },
      { key: "customer", label: "Customer", type: "text", sortable: true },
      { key: "items", label: "Items", type: "int", sortable: true, align: "right" },
      { key: "total", label: "Total", type: "money", sortable: true, align: "right" },
      { key: "paymentMethod", label: "Payment Method", type: "text", sortable: true },
      { key: "paymentStatus", label: "Payment Status", type: "status", sortable: true },
      { key: "status", label: "Order Status", type: "status", sortable: true },
    ],
    filters: ["range", "orderStatus", "paymentStatus", "customer", "channel"],
    summaryCards: [
      { key: "totalOrders", label: "Total Orders", type: "int" },
      { key: "pendingOrders", label: "Pending Orders", type: "int" },
      { key: "completedOrders", label: "Completed Orders", type: "int" },
      { key: "cancelledOrders", label: "Cancelled Orders", type: "int" },
      { key: "totalAmount", label: "Total Order Amount", type: "money" },
    ],
    totalRowKeys: ["items", "total"],
  },

  // ── C. Inventory Reports ───────────────────────────────────────────────────
  {
    id: "inventory-stock",
    name: "Inventory / Stock Report",
    category: "inventory",
    description: "Stock movement per product for the selected period — Current Stock = Opening Stock + Stock In − Stock Out.",
    defaultRange: "this_month",
    defaultSort: { sort: "product", dir: "asc" },
    columns: [
      { key: "product", label: "Product", type: "text", sortable: true },
      { key: "category", label: "Category", type: "text", sortable: true },
      { key: "openingStock", label: "Opening Stock", type: "int", sortable: true, align: "right" },
      { key: "stockIn", label: "Stock In", type: "int", sortable: true, align: "right" },
      { key: "stockOut", label: "Stock Out", type: "int", sortable: true, align: "right" },
      { key: "currentStock", label: "Current Stock", type: "int", sortable: true, align: "right" },
      { key: "minimumStock", label: "Minimum Stock", type: "int", sortable: true, align: "right" },
      { key: "status", label: "Status", type: "status", sortable: true },
    ],
    filters: ["range", "category", "brand", "stockStatus"],
    summaryCards: [
      { key: "totalProducts", label: "Total Products", type: "int" },
      { key: "totalStockItems", label: "Total Stock Items", type: "int" },
      { key: "lowStockProducts", label: "Low-Stock Products", type: "int" },
      { key: "outOfStockProducts", label: "Out-of-Stock Products", type: "int" },
    ],
    totalRowKeys: ["openingStock", "stockIn", "stockOut", "currentStock"],
  },
  {
    id: "low-stock",
    name: "Low-Stock Report",
    category: "inventory",
    description: "Products whose current stock has reached or fallen below their minimum stock level.",
    defaultRange: "this_month",
    defaultSort: { sort: "difference", dir: "asc" },
    columns: [
      { key: "product", label: "Product", type: "text", sortable: true },
      { key: "category", label: "Category", type: "text", sortable: true },
      { key: "currentStock", label: "Current Stock", type: "int", sortable: true, align: "right" },
      { key: "minimumStock", label: "Minimum Stock", type: "int", sortable: true, align: "right" },
      { key: "difference", label: "Difference", type: "int", sortable: true, align: "right" },
      { key: "status", label: "Status", type: "status", sortable: true },
    ],
    filters: ["category", "brand", "stockStatus"],
    summaryCards: [
      { key: "lowStockProducts", label: "Low Stock", type: "int" },
      { key: "outOfStockProducts", label: "Out of Stock", type: "int" },
      { key: "totalUnitsShort", label: "Units Short", type: "int" },
      { key: "affectedCategories", label: "Categories Affected", type: "int" },
    ],
    totalRowKeys: [],
  },

  // ── D. Additional Reports ──────────────────────────────────────────────────
  {
    id: "returns-refunds",
    name: "Sales Return / Refund Report",
    category: "additional",
    description: "Sales that were returned, refunded, or voided, with reasons.",
    defaultRange: "this_month",
    defaultSort: { sort: "datetime", dir: "desc" },
    columns: [
      { key: "saleId", label: "Sale ID", type: "text", sortable: true },
      { key: "datetime", label: "Date", type: "datetime", sortable: true },
      { key: "customer", label: "Customer", type: "text", sortable: true },
      { key: "product", label: "Product", type: "text", sortable: true },
      { key: "qty", label: "Qty", type: "int", sortable: true, align: "right" },
      { key: "amount", label: "Amount", type: "money", sortable: true, align: "right" },
      { key: "reason", label: "Reason", type: "text", sortable: true },
      { key: "status", label: "Status", type: "status", sortable: true },
    ],
    filters: ["range", "cashier", "returnStatus", "returnReason"],
    summaryCards: [
      { key: "totalReturns", label: "Total Returns", type: "int" },
      { key: "totalReturnedItems", label: "Returned Items", type: "int" },
      { key: "totalRefundAmount", label: "Refund Amount", type: "money" },
      { key: "voidedCount", label: "Voided Sales", type: "int" },
    ],
    totalRowKeys: ["qty", "amount"],
  },
  {
    id: "customer-purchase",
    name: "Customer Purchase Report",
    category: "additional",
    description: "Purchasing activity per customer across all channels.",
    defaultRange: "this_month",
    defaultSort: { sort: "totalSpent", dir: "desc" },
    columns: [
      { key: "customer", label: "Customer", type: "text", sortable: true },
      { key: "totalOrders", label: "Total Orders", type: "int", sortable: true, align: "right" },
      { key: "itemsPurchased", label: "Items Purchased", type: "int", sortable: true, align: "right" },
      { key: "totalSpent", label: "Total Spent", type: "money", sortable: true, align: "right" },
      { key: "averageOrder", label: "Average Order", type: "money", sortable: true, align: "right" },
      { key: "lastPurchase", label: "Last Purchase", type: "date", sortable: true },
    ],
    filters: ["range", "customer", "channel"],
    summaryCards: [
      { key: "totalCustomers", label: "Customers", type: "int" },
      { key: "totalOrders", label: "Total Orders", type: "int" },
      { key: "totalSpent", label: "Total Spent", type: "money" },
      { key: "averageOrderValue", label: "Average Order Value", type: "money" },
    ],
    totalRowKeys: ["totalOrders", "itemsPurchased", "totalSpent"],
  },
];

export const REPORT_MAP = new Map(REPORTS.map((report) => [report.id, report]));

export function getReport(id) {
  return REPORT_MAP.get(id) || null;
}

// Shared filter option lists (static part; dynamic options come from dataset meta)
export const STATIC_FILTER_OPTIONS = {
  channel: [
    { value: "", label: "All Channels" },
    { value: "POS", label: "POS" },
    { value: "ONLINE", label: "Online" },
    { value: "WHOLESALE", label: "Wholesale" },
  ],
  paymentMethod: [
    { value: "", label: "All Methods" },
    { value: "Cash", label: "Cash" },
    { value: "KHQR", label: "KHQR" },
  ],
  saleStatus: [
    { value: "", label: "All Statuses" },
    { value: "OPEN", label: "Open" },
    { value: "COMPLETED", label: "Completed" },
    { value: "VOIDED", label: "Voided" },
    { value: "REFUNDED", label: "Refunded" },
    { value: "PENDING", label: "Pending" },
    { value: "CONFIRMED", label: "Confirmed" },
    { value: "PROCESSING", label: "Processing" },
    { value: "PREPARING", label: "Preparing" },
    { value: "READY", label: "Ready" },
    { value: "SHIPPED", label: "Shipped" },
    { value: "DELIVERED", label: "Delivered" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "RETURNED", label: "Returned" },
  ],
  orderStatus: [
    { value: "", label: "All Statuses" },
    { value: "PENDING", label: "Pending" },
    { value: "CONFIRMED", label: "Confirmed" },
    { value: "PROCESSING", label: "Processing" },
    { value: "PREPARING", label: "Preparing" },
    { value: "READY", label: "Ready" },
    { value: "SHIPPED", label: "Shipped" },
    { value: "DELIVERED", label: "Delivered" },
    { value: "COMPLETED", label: "Completed" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "RETURNED", label: "Returned" },
    { value: "REFUNDED", label: "Refunded" },
  ],
  paymentStatus: [
    { value: "", label: "All Payment Statuses" },
    { value: "PAID", label: "Paid" },
    { value: "PENDING", label: "Pending" },
    { value: "PARTIAL", label: "Partial" },
    { value: "FAILED", label: "Failed" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "REFUNDED", label: "Refunded" },
  ],
  stockStatus: [
    { value: "", label: "All Stock Statuses" },
    { value: "IN_STOCK", label: "In Stock" },
    { value: "LOW_STOCK", label: "Low Stock" },
    { value: "OUT_OF_STOCK", label: "Out of Stock" },
  ],
  returnStatus: [
    { value: "", label: "All Statuses" },
    { value: "REFUNDED", label: "Refunded" },
    { value: "VOIDED", label: "Voided" },
  ],
  returnReason: [
    { value: "", label: "All Reasons" },
    { value: "DEFECTIVE", label: "Defective" },
    { value: "WRONG_ITEM", label: "Wrong Item" },
    { value: "CUSTOMER_CHANGED_MIND", label: "Customer Changed Mind" },
    { value: "EXCESS_ORDER", label: "Excess Order" },
    { value: "EXPIRED", label: "Expired" },
    { value: "OTHER", label: "Other" },
    { value: "VOIDED", label: "Voided at POS" },
  ],
};

export const RANGE_PRESETS = [
  { value: "today", label: "Today" },
  { value: "yesterday", label: "Yesterday" },
  { value: "this_week", label: "This Week" },
  { value: "this_month", label: "This Month" },
  { value: "custom", label: "Custom" },
];
